DROP TABLE if EXISTS car;

CREATE TABLE car(
id  BIGINT SERIAL NOT NULL ,
make VARCHAR (255) not NULL ,
model VARCHAR (255) not NULL ,
YEAR INT(10)  not NULL
);

DROP TABLE if EXISTS T_HOUSE;

CREATE TABLE T_HOUSE(
id  BIGINT SERIAL NOT NULL UNIQUE,
name VARCHAR (255) not NULL ,
square VARCHAR (255) not NULL ,
city VARCHAR (20) not NULL
);


CREATE TABLE "T_USER" (
"ID" NUMBER(9,0) NOT NULL ,
"NAME" VARCHAR2(255) NULL ,
"NICK_NAME" VARCHAR2(255) NULL ,
"PASSWORD" VARCHAR2(255) NULL ,
"AGE" NUMBER(5,0) NULL ,
"STATUS" CHAR(1) NULL ,
PRIMARY KEY ("ID")
)
NOCOMPRESS
;

COMMENT ON COLUMN "ACTIVITY"."NewTable"."NAME" IS '姓名';

COMMENT ON COLUMN "ACTIVITY"."NewTable"."NICK_NAME" IS '昵称';

COMMENT ON COLUMN "ACTIVITY"."NewTable"."STATUS" IS '状态，1：正常，2：锁定，3：不完整用户';


CREATE SEQUENCE "ACTIVITY"."SEQ_USER"
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 10000000
 START WITH 100
 NOCACHE ;